source 'https://github.com/yuemoj/BGFMDB.git'
source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
target 'BGFMDB-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BGFMDB-Example
#  pod 'BGFMDB-Privacy', :source=>'https://github.com/yuemoj/BGFMDB.git'
  pod 'BGFMDB-Privacy', '~> 1.0.0'#, :source=>'https://github.com/yuemoj/BGFMDB.git'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
